### ISSUE TITLE
Packages for Ubuntu Utopic/Vivid in the PPA

### ISSUE THREAD

**Issue by leesah** [ambrop72/badvpn#11]
I've been missing it since last upgrade of my OS. Is the PPA going to be maintained in the future?

**Comment by ambrop72** [comment]
Maybe.. sometimes.. I hope I haven't lost the VM where I had this set up and the GPG keys.

**Comment by leesah** [comment]
Doesn't sound good... :-(

So now the recommended way is to compile locally?

**Comment by ambrop72** [comment]
Please ask your distribution maintainers to provide a package. I will not be providing Ubuntu packages; sorry about that.
