### ISSUE TITLE
move_first_timers crash

### ISSUE THREAD

**Issue by xDragonZ** [ambrop72/badvpn#112]
Noticed on reconnection it will crash after [tun2socks.c#L946](https://github.com/ambrop72/badvpn/blob/master/tun2socks/tun2socks.c#L946) failed

stacktrace leads to:
**BReactor_badvpn.c** - [Line 117](https://github.com/ambrop72/badvpn/blob/master/system/BReactor_badvpn.c#L117) at `move_first_timers (BReactor *bsys)`
 **tun2socks.c** - `BReactor_Exec(&ss);`

any idea why this happens?

**Comment by bitmold** [comment]
Hey, actually this exact issue happens in the very outdated fork of badvpn that is used in https://github.com/guardianproject/orbot. Specifically in issue 410 https://github.com/guardianproject/orbot/issues/410 

Did you happen to have any luck resolving this?
