### ISSUE TITLE
Can tun2socks support UDP?

### ISSUE THREAD

**Issue by TommyJerryMairo** [ambrop72/badvpn#15]
I have read the README.md and found this:

    The tun2socks program "socksifes" TCP connections at the network layer.

It seems that the tun2socks does not support UPD. 
And it seems that the BadVPN do not support confounding data yet.

So, I believe that if the BadVPN can support confounding data (like obfs) or enable tun2socks to support UDP, it would be more popular, for many people in China Mainland need tools to fight against GFW(the Great Firewall of China), to connect to the real Internet.

Thank you.

**Comment by ambrop72** [comment]
Hi,
Tun2socks can support UDP through an udpgw daemon running on a remote host (on the remote side of the SOCKS). Please see details here, https://code.google.com/archive/p/badvpn/wikis/tun2socks.wiki

**Comment by ambrop72** [comment]
Also I should emphasize that tun2socks was not intended for bypassing firewalls or censoring systems, and I have no plans to add any features specifically for that. It is just a way to transparently forward traffic through a SOCK server, not much more.

**Comment by TommyJerryMairo** [comment]
Ok, tks.

**Comment by chitujsq** [comment]
@ambrop72 
"Currently tun2socks does not support UDP directly through SOCKS (the UDP feature of SOCKS). But note that the utility of such a feature depends on the SOCKS server anyway"

if I use dante(support UDP) as the socks server,  did I need udpgw daemon running on the same server? can you tell me the flow of forward udp by useing udpgw, I guess as follow :
tun--->tun2socks---->UdpGwClient---->SocksUdpGwClient-- ->socks_client--->socks_server--->udpgw ?

**Comment by ambrop72** [comment]
The udpgw mechanism works such that tun2socks establishes a TCP connection to udpgw, through the SOCKS server. Udpgw sends and receives UDP packets using normal OS network access.

This is how it works, but I can't say what is the right solution for you. It may not be useful for your case in the first place (if you have no reasonable place to deploy udpgw).

**Comment by Un1Gfn** [comment]
[shadowsocks/badvpn](https://github.com/shadowsocks/badvpn) fork supports UDP.

Checkout `--enable-udprelay` in [this file](https://github.com/shadowsocks/badvpn/blob/shadowsocks-android/tun2socks/tun2socks.c).

**Comment by edsburke** [comment]
> ~[shadowsocks/badvpn](https://github.com/shadowsocks/badvpn) fork supports UDP directly~
> 
> ~Checkout `--enable-udprelay` in [tun2socks.c](https://github.com/shadowsocks/badvpn/blob/shadowsocks-android/tun2socks/tun2socks.c)~
> 
> It seems that direct UDP support is now possible w/ [`--socks5-udp` parameter](https://github.com/ambrop72/badvpn/blob/master/tun2socks/tun2socks.c#L748)
> 
> You should build the current git version instead of 1.999.130, which is from 2015

Can anyone explain the --socks5-udp is official feature to let tun2socks to proxify UDP traffic? Thanks.
