### ISSUE TITLE
DeviceIoControl(TAP_IOCTL_GET_MTU) failed

### ISSUE THREAD

**Issue by iceberg1369** [ambrop72/badvpn#16]
I get folowing error when I use NDIS6 driver but it's ok with NDIS5
NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.128
INFO(BTap): Looking for TAP-Win32 with component ID tap0901, name Local Area Con
nection 2
INFO(BTap): Opening device \\.\Global\{B9955714-34F4-4846-BBE3-79F734861EF2}.tap

ERROR(BTap): DeviceIoControl(TAP_IOCTL_GET_MTU) failed
ERROR(tun2socks): BTap_Init failed
NOTICE(tun2socks): exiting

**Comment by ambrop72** [comment]
Hey,
This is a known issue. I don't know what the exact cause, but it is related to some change in the TAP-Win32 driver. You can try using an older / different version of the driver. As far as I know, there are at least two packages, the driver that comes with OpenVPN, and a separate package for the driver only (both available [here](https://openvpn.net/index.php/open-source/downloads.html)).

Please understand that I don't have much incentive to support Windows.

**Comment by iceberg1369** [comment]
thanks for the reply

**Comment by DerPopo** [comment]
It seems like the driver wants the mtu pointer to be passed as an input parameter. Changing line 273 of BTap.c to this fixed the issue for me :
```
if (!DeviceIoControl(o->device, TAP_IOCTL_GET_MTU, &umtu, sizeof(umtu), &umtu, sizeof(umtu), &len, NULL))
```
