### ISSUE TITLE
Can I use DNS via tun2socks?

### ISSUE THREAD

**Issue by minimedj** [ambrop72/badvpn#18]
I have complete `tun2socks` setup. I am running `tun2socks` with UDP forwarding enabled. TCP seems to work fine.

I want me DNS requests go via `tun2socks` UDP forwarding facilities.

Is it expected to work?

So far I see that `badvpn_tun2socks` captures UDP packets but I never got an answer...

**Comment by grandkarabas** [comment]
Hello, @minimedj 
Could you please explain to me what solution you had found? I have the same problem currently.
Thank you in advance

**Comment by voxsoftware** [comment]
Same problem, ip directly works, but dns no. How redirect dns queries to socks?

**Comment by juanpagfe** [comment]
> Same problem, ip directly works, but dns no. How redirect dns queries to socks?

You have to follow [these instructions](https://github.com/ambrop72/badvpn/wiki/Tun2socks#udp-forwarding) to get udp traffic working.
