### ISSUE TITLE
ERROR(BTap): DeviceIoControl(TAP_IOCTL_GET_MTU) failed

### ISSUE THREAD

**Issue by osklil** [ambrop72/badvpn#2]
Hello
I'm trying to run badvpn-tun2socks in Windows and after creating the TAP adapter I get this error:

ERROR(BTap): DeviceIoControl(TAP_IOCTL_GET_MTU) failed

According to http://openvpn.net/index.php/open-source/documentation/install.html you cannot programmatically set the MTU:

"Currently on Windows, the only way to change the TAP-Windows MTU is to go to the adapter advanced properties and do it manually."

and I guess explains why TAP_IOCTL_GET_MTU fails. Perhaps an option to assume a MTU should be added for windows platforms? I.e. --mtu=1500

Oskar

**Comment by Evengard** [comment]
Seems like it bugs with the NDIS 6 driver, but is fine with the NDIS 5 one. NDIS 5 one works well though on Win7 and later, but badvpn-tun2socks gets this exact error on NDIS 6 driver from OpenVPN.

**Comment by gvlx** [comment]
Microsoft Windows [version 6.1.7601] 64bit
 - fails with tap-windows-9.21.1.exe (NDIS 6) 
 - works with tap-windows-9.9.2_3.exe (NDIS 5)

Files from https://openvpn.net/index.php/download/community-downloads.html

**Comment by andrewkboyd** [comment]
NDIS 6 fails if you don't pass input parameters (even when none are needed) to the DeviceIoControl method. 

So the output parameters [here](https://github.com/ambrop72/badvpn/blob/e4c152027c7e5f61fa4b8eaace45546635dae643/tuntap/BTap.c#L273-L276) need to be the same as the input parameters or NDIS6 throws an error.

I would submit these changes if I could, but I can't

**Comment by muxq** [comment]
Maybe the process is already running

**Comment by bemasc** [comment]
I know I'm about 4 years late to this party, but this compatibility issue has now been fixed tap-windows6 master (https://github.com/OpenVPN/tap-windows6/pull/71), and the fix should be present in the next release.

**Comment by tobiastromm** [comment]
Hi @bemasc , I am having the same issue here with OpenVPN 2.4.7 [2019.02.21].

This is not fixed yet?

Thank you.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
@tobiastromm its not so difficult, just follow: https://github.com/ambrop72/badvpn/blob/master/BUILD-WINDOWS-VisualStudio.md and get working version ;)

**Comment by tobiastromm** [comment]
Yep, I already do that some years ago for BadVPN server 1.999.129.
