### ISSUE TITLE
tun2socks won't work with tun1

### ISSUE THREAD

**Issue by hillz1** [ambrop72/badvpn#20]
I have openvpn installed and it's using `tun0` so I created another tun device, here's my tun2socks command:
`badvpn-tun2socks --tundev tun1 --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr 192.168.1.1:1080 --udpgw-remote-server-addr 192.168.1.1:7300 > /dev/null &`
Here's my `route` commands:
```
openvpn --mktun --dev tun1 --user root # Create tun1
ifconfig tun1 10.0.0.1 netmask 255.255.255.0
#DEFAULT#
route del -net 0.0.0.0 netmask 0.0.0.0 gw 0.0.0.0
route add default gw 10.0.0.2 metric 6
#INDOSAT#
route add 10.19.19.19 gw 10.64.64.64 metric 5 # My ISP Proxy
route add 202.152.165.39 gw 10.64.64.64 metric 5 #My ISP DNS
route add 114.5.5.77 gw 10.64.64.64 metric 5 # My ISP DNS
```
After executing those commands my internet just won't work, here are some screenshots:
http://s28.postimg.org/ymba2a2n1/image.png
http://s14.postimg.org/z8swl0141/image.png

**Comment by hillz1** [comment]
But somehow it's working when using `tun0` check out this screenshot http://s8.postimg.org/r9fem5rg5/image.png

**Comment by ambrop72** [comment]
Hey,
Sorry I have no idea, but surely this is a problem in your configuration, and nothing in tun2socks itself.
Closing because presumably you've solved your issue...

**Comment by hillz1** [comment]
Yes it's been solved and I forgot to close this issue, I'm sorry
