### ISSUE TITLE
 ERROR(tun2socks): device error (android)

### ISSUE THREAD

**Issue by kooroshh** [ambrop72/badvpn#23]
hi , 
when i want to run tun2socks on android i've got this error 

> 
> 06-19 00:01:33.674 14881-17117/net.test.tun2sockstest D/RootShell v1.3: Executing: /data/data/net.test.tun2sockstest/tun2socks --netif-ipaddr 25.25.25.2 --netif-netmask 255.255.255.0 --socks-server-addr 192.168.1.200:808 --tunfd 40 --tunmtu 1500 --logger stdout --loglevel 5 --pid /data/data/net.test.tun2sockstest/tun2socks.pid with context: NORMAL
> 06-19 00:01:33.694 17123-17123/? D/tun2socks: NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.127
> 06-19 00:01:33.694 17125-17125/? D/tun2socks: DEBUG(BReactor): Reactor initializing
> 06-19 00:01:33.694 17125-17125/? D/tun2socks: DEBUG(BSignal): BSignal initializing
> 06-19 00:01:33.694 17125-17125/? D/tun2socks: ERROR(BReactor): epoll_ctl failed: 17
> 06-19 00:01:33.694 17125-17125/? D/tun2socks: ERROR(BTap): BReactor_AddFileDescriptor failed
> 06-19 00:01:33.694 17125-17125/? D/tun2socks: ERROR(tun2socks): BTap_Init2 failed
> 06-19 00:01:33.694 17125-17125/? D/tun2socks: DEBUG(BReactor): Reactor freeing
> 06-19 00:01:33.694 17125-17125/? D/tun2socks: NOTICE(tun2socks): exiting
> 06-19 00:01:33.694 14881-17118/net.test.tun2sockstest D/RootShell v1.3: Read all output
> 06-19 00:01:35.334 14881-17118/net.test.tun2sockstest D/TUN2SOCKS: 0
> 06-19 00:01:35.334 14881-17118/net.test.tun2sockstest D/RootShell v1.3: Command 0 finished.

**Comment by ambrop72** [comment]
Hi,

I've never seen this before. The log is telling you that epoll_ctl failed with errno 17 when trying to register the tuntap file descriptor with the epoll instance. While I'm not 100% sure about the errnos on Android, this seems to correspond to EEXIST, which the epoll_ctl manpage claims happens when the file descriptor is already registered with epoll. While I don't know what the cause could be, maybe that can help you find any mistake in your code.

**Comment by ambrop72** [comment]
Also a strace log is likely to be helpful.

**Comment by kooroshh** [comment]
thanks for your response , 
the first Log occurs when i use the getFd() of ParcelFileDescriptor
but when i use the detachFd() this one occurs : 

> 06-19 01:22:58.738 20996-23404/net.test.tun2sockstest D/RootShell v1.3: Executing: /data/data/net.test.tun2sockstest/tun2socks --netif-ipaddr 25.25.25.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:808 --tunfd 37 --tunmtu 1500 --logger stdout --loglevel 5 --pid /data/data/net.test.tun2sockstest/tun2socks.pid with context: NORMAL
> 06-19 01:22:58.768 23409-23409/? D/tun2socks: NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.127
> 06-19 01:22:58.768 23410-23410/? D/tun2socks: DEBUG(BReactor): Reactor initializing
> 06-19 01:22:58.768 23410-23410/? D/tun2socks: DEBUG(BSignal): BSignal initializing
> 06-19 01:22:58.768 20996-23405/net.test.tun2sockstest D/RootShell v1.3: Read all output
> 06-19 01:22:58.768 23410-23410/? D/tun2socks: NOTICE(tun2socks): entering event loop
> 06-19 01:22:58.768 23410-23410/? D/tun2socks: DEBUG(BReactor): Entering event loop
> 06-19 01:22:58.768 23410-23410/? D/tun2socks: DEBUG(tun2socks): lwip init
> 06-19 01:22:58.768 23410-23410/? D/tun2socks: DEBUG(tun2socks): netif func init
> 06-19 01:22:58.778 23410-23410/? D/tun2socks: ERROR(tun2socks): device error
> 06-19 01:22:58.778 23410-23410/? D/tun2socks: NOTICE(tun2socks): tearing down
> 06-19 01:22:58.778 23410-23410/? D/tun2socks: DEBUG(BReactor): Exiting event loop, exit code 1
> 06-19 01:22:58.778 23410-23410/? D/tun2socks: NOTICE(tun2socks): Free TCP connections
> 06-19 01:22:58.778 23410-23410/? D/tun2socks: DEBUG(BReactor): Reactor freeing
> 06-19 01:22:58.778 23410-23410/? D/tun2socks: NOTICE(tun2socks): exiting

**Comment by kooroshh** [comment]
from the Android Documentations : 

> detachFd()
> Return the native fd int for this ParcelFileDescriptor and detach it from the object here.
>

**Comment by ambrop72** [comment]
Seems like there is an error in a read() of the tuntap file descriptor. You can use strace to get more details, or change the code to print errno (BTap.c, find the two instanced of read() calls). I suspect it has something to do with the transfer of the file descriptor to the child process.

**Comment by ambrop72** [comment]
Maybe try to close() the file descriptor in the java code after tun2socks has been started?

**Comment by kooroshh** [comment]
i'm using the compiled binary , i have no access to the source (due the lack of ndk support in windows)

**Comment by kooroshh** [comment]
you helped me so much , thank you , the problem was child process hasn't access to the FD number . 
Problem Solved via using libsystem.so
