### ISSUE TITLE
Netmask vs prefix and cidr

### ISSUE THREAD

**Issue by gsib** [ambrop72/badvpn#28]
Is it possible to use netmask in the ncd as compared to having both prefix and cidr in the network config?

**Comment by ambrop72** [comment]
Hi,

The valid syntaxes are shown in the source code, e.g. for net.ipv4.addr [1]:

net.ipv4.addr("eth0", "192.168.123.4", "24");
net.ipv4.addr("eth0", "192.168.123.4/24");

If you have a netmask you need to use [2]:

ipv4_mask_to_prefix("255.255.255.0") prefix;
net.ipv4.addr("eth0", "192.168.123.4", prefix);


[1]
https://github.com/ambrop72/badvpn/blob/master/ncd/modules/net_ipv4_addr.c
[2] https://github.com/ambrop72/badvpn/blob/master/ncd/modules/netmask.c

**Comment by gsib** [comment]
Ok thanks.
