### ISSUE TITLE
How to protect udp channel.

### ISSUE THREAD

**Issue by happypeng** [ambrop72/badvpn#30]
i don't want to forward udp data, what i should do?
I put the udpgwServerAddress is NULL and udpgwTransparentDNS is false,but it 's alwasy forward upd data.

thanks a lot ,
and sorry for my bad english.

**Comment by ambrop72** [comment]
Hi,
Tun2socks will not forward UDP packets if there is no UDPGW server address specified. There is simply no other mechanism implemented that could forward UDP, at least in the tun2socks version in this repository.
