### ISSUE TITLE
Multiple DNS servers

### ISSUE THREAD

**Issue by gsib** [ambrop72/badvpn#31]
Hi,
In NCD, I have noticed that dhcp.dns_servers is an array which obtained is not comma separated or spaces. e.g. 123.2.2.5123.2.2.8
How would I obtain the first entry in the array?
Regards,
George

**Comment by ambrop72** [comment]
Hi,
The functions available in ncd/modules/value.c implement all sorts of value access and manipulation. See the examples for this below. I'm assuming you want to handle the possibility that there is no server at all.

```
# Solution 1
value(dhcp.dns_servers) dns_servers;
If (@val_greater(dns_servers.length, "0")) { # val_greater defined in ncd/modules/basic_functions.c
    dns_servers->get("0") first_server; # get errors on nonexisting element, so we check existance before
    println(@concat("The first server is ", first_server));
};

# Solution 2
value(dhcp.dns_servers) dns_servers;
dns_servers->try_get("0") first_server; # try_get doesn't error on nonexisting element
If (first_server.exists) {
    println(@concat("The first server is ", first_server));
};
```

Does this work for you?

**Comment by gsib** [comment]
It should work thanks Ambroz

**Comment by gsib** [comment]
Hi,

I am having problem:

dhcp.dns_servers

returns

192.168.8.1192.168.8.1

Regards,
G

**Comment by ambrop72** [comment]
The dns_servers is a list of strings. I don't know what you mean by "returns". One way to print it out is by `println(@encode_value(dhcp.dns_servers));` and you will get something like `{"1.2.3.4","5.6.7.8"}`. You could only get what you say if you concatenated the strings in the list, e.g. `println(@concatlist(dhcp.dns_servers));`.

Do any of my proposed solutions for getting the first element of the list not work?

**Comment by ambrop72** [comment]
Also I don't understand what you are trying to do. Note that the built-in command `net.ipv4.dhcp` which is used for management of the DNS servers already accepts a list - it is pretty much made to be passed `dhcp.dns_servers` directly.
