### ISSUE TITLE
Unexpected behavior with Windows RRAS and TAP_IOCTL_GET_MTU error

### ISSUE THREAD

**Issue by marukka** [ambrop72/badvpn#36]
I have two virtual machines, the first VM connects to Tor, runs badvpn 1.999.128 and Windows Routing & Remote Access (RRAS) on Windows Server 2016, and a second virtual machine which runs Windows 10 and Firefox. The Firefox VM is configured to use the Tor VM as its gateway and DNS server. Whenever I try to use RRAS NAT to share the Tor network connection with the Firefox VM, and configure RRAS NAT with the TAP adapter as the Public/Full interface, any internet requests for the Firefox VM have their traffic routed to the public internet. If I use internet connection sharing instead of RRAS NAT, everything works as expected and the Firefox VM has its traffic routed over the Tor network. Can you think of why RRAS's NAT feature when using the TAP adapter as the Full/Public interface would not only not route over the Tor network but do so over the public internet instead? This RRAS configuration works fine when I use it with a OpenVPN connection's TAP adapter in a different set of virtual machines.

The Tor VM has 3 interfaces, Ethernet0 is 10.5.1.6, Ethernet1 is 10.7.2.0 and the TAP adapter (Ethernet) is 10.6.4.1.
 I am running badvpn-tun2socks with this command:
badvpn-tun2socks.exe --tundev tap0901:Ethernet:10.6.4.1:10.6.0.0:255.255.0.0 --netif-ipaddr 10.6.4.2 --netif-netmask 255.255.0.0 --socks-server-addr 127.0.0.1:9050
The TAP adapter is configured with the IP 10.6.4.1 and does not have a gateway specified.

Can you think of what might be causing this? I would try it with a more recent version of the TAP adapter driver but I receive the TAP_IOCTL_GET_MTU error specified in the following bug report when using OpenVPN 2.3.12, and have to use the workaround (NDIS 5 driver). It seems that andrewkboyd's fix to this bug was not implemented in the version of badvpn i'm using.

https://github.com/ambrop72/badvpn/issues/2

**Comment by ambrop72** [comment]
Hi,
This is a known issue. It has recently been fixed in the code.
As I do not provide Windows binaries at the time, you can compile following the instructions in https://github.com/ambrop72/badvpn/blob/master/BUILD-WINDOWS.txt . Or you can try to build on Windows with CMake/VisualStudio, if you disable building all components except tun2socks, as then you don't need the NSS and OpenSSL libs.

**Comment by marukka** [comment]
Thanks, i'll try building it tomorrow and ill report back.

**Comment by marukka** [comment]
I just checked that file and it says it can only be built on Linux? Is there any way at all to the build this on Windows?

**Comment by ambrop72** [comment]
Use the Windows version of CMake and configure building with Visual Studio. Run CMake configuration with options BUILD_NOTHING_BY_DEFAULT=OFF BUILD_TUN2SOCKS=ON. After configuration with CMake is done, open the generated solution file with Visual Studio and build.

**Comment by marukka** [comment]
I've tried but I receive the following error with Visual Studio 2015 Enterprise. PRIu8, PRIx16 and PRIu16 are not found in system/BAddr.h
<img width="1591" alt="screen shot 2016-11-30 at 11 17 08 am" src="https://cloud.githubusercontent.com/assets/3067075/20763189/9d571a7c-b6ee-11e6-832d-978889d72580.png">

**Comment by ambrop72** [comment]
I just pushed a fix, it should work now.

**Comment by marukka** [comment]
A new error
<img width="961" alt="screen shot 2016-11-30 at 5 46 59 pm" src="https://cloud.githubusercontent.com/assets/3067075/20776285/2656155e-b725-11e6-8e9c-9aa9056b28d4.png">

**Comment by marukka** [comment]
In addition there were similar errors related to NDEBUG being undefined and as a result there being structs without any members in BLog.c, debugerror.h and BTime.c. Commending out the #ifndef from all the files allowed the product to build successfully.

**Comment by marukka** [comment]
Unfortunately I still have experience the unexpected behavior with RRAS with the TAP adapter included in OpenVPN 2.3.13 on a new VM. 24.148.92.25 is my real IP and not a Tor exit node.

<img width="1680" alt="screen shot 2016-11-30 at 6 25 00 pm" src="https://cloud.githubusercontent.com/assets/3067075/20777124/853503dc-b72a-11e6-967a-0e71237df090.png">
<img width="1680" alt="screen shot 2016-11-30 at 6 26 05 pm" src="https://cloud.githubusercontent.com/assets/3067075/20777126/8cfa11f2-b72a-11e6-8234-16ebfc67b141.png">

And showing my RRAS configuration works just fine when used with a OpenVPN based connection instead of badvpn-tun2socks
<img width="1680" alt="screen shot 2016-11-30 at 6 27 40 pm" src="https://cloud.githubusercontent.com/assets/3067075/20777220/25ba308e-b72b-11e6-997b-bc18136967b3.png">
<img width="1680" alt="screen shot 2016-11-30 at 6 30 00 pm" src="https://cloud.githubusercontent.com/assets/3067075/20777222/29525bd6-b72b-11e6-833f-c1c5b357e213.png">

**Comment by ambrop72** [comment]
Ah, the new version only resolves the TAP GET_MTU error, looks like I didn't fully understand what your issue is.
Seems like no traffic is being routed into the TAP interface.
Does "ping 10.6.1.2" work? Can you check with Wireshark the traffic on the TAP interface?
I understand you specifically told RRAS NAT to route into the TAP interface, and it's not doing that?
Otherwise I doubt that I will be able to help much because I'm not familiar with Windows networking.

**Comment by zpfsqzyl** [comment]
@marukka can you upload your complicated files? I don't have a linux device, thanks in advance.

**Comment by marukka** [comment]
@zpfsqzyl i'm sorry, i dont understand what you mean by complicated files. I don't understand what why you bring up not having a linux device as my issue is regarding this running on Windows.

Also I suppose I should probably figure out where i left off so i can continue working with ambrop72. I just ended up using ICS instead of RRAS.

**Comment by ambrop72** [comment]
the TAP_IOCTL_GET_MTU issue had been solved, closing
