### ISSUE TITLE
TUN device issues (Windows 8.1)

### ISSUE THREAD

**Issue by samuel-allan** [ambrop72/badvpn#37]
Again, apologies if this is a a very specific question, but I'm having trouble getting the Tun2Socks part of this project to work on Windows 8.1 because of some problem with the TAP/TUN drivers (or more specifically the communications that take place between the driver and Tun2Socks). Currently I'm using OpenVPN's 'Add a new TAP virtual ethernet adapter' function, which creates a device 'tap0901'. This works out just fine (when run with Adminstrative priveleges), and OpenVPN seems to be able to use it fine as well. The problem occurs when I try to pass on the device to Tun2Socks, where upon running the command: `badvpn-tun2socks.exe --tundev tap0901 --netif-ipaddr 127.0.0.1 --netif-netmask 255.255.255.0 --socks-server-addr SOMEADDRESS:80` I get the following output:
```

NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
DEBUG(BReactor): Reactor initializing
DEBUG(BSignal): BSignal initializing
split_spec: missing separator number 1
ERROR(BTap): failed to parse TUN device specification
ERROR(tun2socks): BTap_Init failed
DEBUG(BReactor): Reactor freeing
NOTICE(tun2socks): exiting
```

I have tried running in Admin mode, using different identifiers (device name, device display name, friendly name, in fact almost every single property visible in the device manager). I would love to hear some help from you regarding this, as I depend a lot on this tool, which has no replacement and which I'd love to help out on once I'm finished with my particular project.

**Comment by ambrop72** [comment]
Hi,
The syntax for --tundev is:
`tap0901:<human_name_of_TUN_device>:<IP-address>:<network-address>:<network-mask>`
Here `<IP-address>` is the IP address of the Windows TAP-Win32 interface as configured (not the address of tun2socks).

**Comment by samuel-allan** [comment]
Thanks a lot! That helped immensely.

**Comment by samuel-allan** [comment]
@ambrop72, One other question, if this were bundled into a tool of some kind how would I go best about trying to find the IP-address, network-address and network-mask? And also what is the exact meaning of `netif-ipaddr` and `netif-netmask`? Thanks a lot for your time, hope I'm being helpful :D

**Comment by ambrop72** [comment]
Hi,
1) Usually you configure these things manually in the Windows network interface settings (for the TAP interface). Surely Windows provides an API to find these, if you need to.
2) `netif-ipaddr` and `netif-netmask` are the IP address and subnet masks that tun2socks assumes on the virtual interface. The former is the IP that you need to route to in order to get traffic from tun2socks.

Here is a little tutorial for tun2socks (which I've just copied from the old docs on GoogleCode): https://github.com/ambrop72/badvpn/wiki/Tun2socks

**Comment by samuel-allan** [comment]
Hi thanks a lot man! I still can't get it to work (although tun2socks works just fine), I feel like a real newbie, so apologies if I'm making you feel like you're explaining something to a 2 year old, but for some reason once everything is setup it doesn't seem to be redirecting any of the system's traffic through the SOCKS proxy. I'm also really confused by this (warning: some real newbie stuff to follow) <IP_of_SSH_server> <IP_of_original_gateway>, in particular what does IP of original gateway refer to? Would it be the local port (entry) of the proxy, or 10.0.0.2 (an assigned IP in the example, assigned to tun2socks). And last thing, I'm having to work with SOCKS proxies instead of tunneling over SSH, does this involve any additional steps? Thanks a lot for the awesome help, this is fairly new to me (this particular area) so I'm a bit lost, but I got the first part to work (tun2socks) and now routing is the only problem. Huge thanks again, hope I'll get it to work soon :P Cheers!

**Comment by ambrop72** [comment]
Really what you need to achieve is:
- Get appropriate traffic routed into the TUN interface. Use the route command to achieve that. Verify with Wireshark if the routing is working, by capturing on the TUN interface.
- Make sure that adding the tun2socks route didn't create a forwarding loop. That is, check that the connection from tun2socks to the SOCKS server does not get routed into tun2socks, and possibly, if the SOCKS server is local, that the corresponding connections made by the SOCKS server (whatever form they be) are not routed into tun2socks, but through your real Internet gateway as appropriate (the "original gateway").

**Comment by samuel-allan** [comment]
Oh thanks a lot! I'll try these out asap and let you know how it goes, thanks again :D looks like I get most of it now.

**Comment by samuel-allan** [comment]
Hi! Thanks a lot! Works like a charm, one of the issues was, I was misunderstanding how the 'route' command in windows works, anyway, cheers!
