### ISSUE TITLE
TAP_IOCTL_CONFIG_TUN fails

### ISSUE THREAD

**Issue by BenoitDuffez** [ambrop72/badvpn#4]
Hi,
I have Win7, running console prompt as Administrator. I have installed the latest OpenVPN binary and added one tap interface that I renamed to "tap_badvpn".
Here's what I do to set up badvpn:

```
E:\softs\badvpn-1.999.128-win32\bin>badvpn-tun2socks.exe --tundev tap0901:tap_badvpn:10.0.0.1:10.0.0.255:255.255.255.0 --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:8081
NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.128
INFO(BTap): Looking for TAP-Win32 with component ID tap0901, name tap_badvpn
INFO(BTap): Opening device \\.\Global\{38B72935-00B2-4896-B172-D8888929552C}.tap
ERROR(BTap): DeviceIoControl(TAP_IOCTL_CONFIG_TUN) failed
ERROR(tun2socks): BTap_Init failed
NOTICE(tun2socks): exiting
```

I don't know if my badvpn binaries are up to date. I don't have a Windows compiler.

Is there anything to configure on the tap device? I have set up a static IP address as 10.0.0.1 but it didn't help.

Thanks a lot for your software and support.

**Comment by TongxiJi** [comment]
Try to reinstall the tap driver.

**Comment by BenoitDuffez** [comment]
I did at that time but that request is no longer relevant. Thanks.

**Comment by ambrop72** [comment]
Tun2socks currently doesn't work with the TAP-Windows NDIS6 driver. To make it work it is necessary to install the older NDIS5 driver.
Remember that I'm not stopping anyone from fixing tun2socks to work with the new driver :)
