### ISSUE TITLE
UDP performance

### ISSUE THREAD

**Issue by khiempg** [ambrop72/badvpn#41]
Hi all,

I am using tun2socks like as proxy client, I have no problem with performance with TCP( around 300Mbps in my environment by iperf).
But performance for UDP is not good (under 20 Mbps), have packet loss and droped at tun2socks (Out of buffer):

https://github.com/ambrop72/badvpn/blob/master/udpgw_client/UdpGwClient.c (line 340 )
 `if (!BufferWriter_StartPacket(con->send_if, &out)) {
        BLog(BLOG_ERROR, "out of buffer");
        return;
  }`
Seem that room of buffer is not enough.
Is there any way to improve UDP performance or increase buffer for sending UDP packet.a

Thank you very much.

**Comment by ambrop72** [comment]
Hi,
You can set the output buffer size for the UDPGW connection with the `--udpgw-connection-buffer-size` command line option. The default is 8 (packets).

**Comment by khiempg** [comment]
Hi,
Thank for your support, I changed to 1024, also on udpgw and performance is getting better. There is no "Out of buffer" in client site, that is great.
But there is some packet loss (compare with no proxy case for UDP, same environment). I did not see any error log on gateway. I changed some parameter in udpgw.h, but there is still packet loss.
Do you give me some comment for process packet loss or debug this case?

One again, thank for quick response.

**Comment by xDragonZ** [comment]
I notice that udpgw used quite amount of port, is there any way to optimize it?

**Comment by ambrop72** [comment]
Hey, by default udpgw lets the OS pick the local port. There is the option to manage the port range manually: `--local-udp-addrs <local_addr>:first_port num_ports". Probably you want <local_addr> to be 0.0.0.0.
