### ISSUE TITLE
Can't access reddit without manually setting up browser's proxy

### ISSUE THREAD

**Issue by hillz2** [ambrop72/badvpn#42]
Hi, I'm sorry this isn't a bug report of tun2socks, this is more like just my curiosity. So reddit is blocked in my country, the only ways to access it are with vpn & ssh tunnel. I use tun2socks with my ssh tunnel, I can access other websites just fine without configuring my browser proxy to my SSH socks proxy but not with reddit. I have to manually setting up a proxy on my browser first to be able to access it. Do you know why that happens ? Is it related to the DNS or anything else? I followed the exact same tutorial as the one you wrote here https://github.com/ambrop72/badvpn/wiki/Tun2socks

**Comment by ambrop72** [comment]
Hi,
You didn't provide any information about what is going wrong. In what way does reddit not load? Wireshark traces of both interfaces should help.

**Comment by hillz2** [comment]
Here's the screenshot when I try to access reddit:
https://s9.postimg.org/alv188nq7/screenshot-2017-04-21_20-00-57.png
Here's the wireshark log:
https://www.dropbox.com/s/cadj6i86onpihlq/reddit.pcapng?dl=0
It seems that the DNS got blocked by blockpage.xl.net.id
