### ISSUE TITLE
Any chance to upgrade lwip to latest version

### ISSUE THREAD

**Issue by wongsyrone** [ambrop72/badvpn#45]
The latest version is 2.0.2 according to http://download.savannah.nongnu.org/releases/lwip/

**Comment by wongsyrone** [comment]
I will do this myself

**Comment by ambrop72** [comment]
Sorry I don't maintain this code regularly anymore. Note that the vanilla lwip is probably not okay, tun2socks needs changes to support binding to all addresses and all ports, in my adaptation that is `tcp_bind_to_netif()`. Probably the fork by VirtualBox has equivalent changes but I don't know how up to date it is.

**Comment by wongsyrone** [comment]
Thanks for the information. I found the diff based on lwip-base-version file: https://gist.github.com/wongsyrone/2a2c134e8f927364e598d2a6e706f4a8

**Comment by wongsyrone** [comment]
Hi, I modified twip latest git HEAD to make it work on tun2socks.

Here goes the commits:

simple copy and paste and updated lwip-base-version to give clear instruction which point we are located
https://github.com/wongsyrone/badvpn/commit/0c0847479ac0b4dbdde97bad003d1bb987fca5e3

update custom folder and drop outdated defs
https://github.com/wongsyrone/badvpn/commit/2422fc5168033fdabb0740697b4f4cf0ce0eab57

the most important changes to lwip to let us be able to bind to all addresses and all ports
https://github.com/wongsyrone/badvpn/commit/8a7797722dbeba68a66406ed74e67e8533e52c28

finally, update tun2socks source code to make it working, please ignore some out-of-tree android changes
https://github.com/wongsyrone/badvpn/commit/3d2e3946b1d219f03d2946f27ef5d8db24d66b0d

another boring change to keep updated, especially for ip addr macro change, since we only need raw api
https://github.com/wongsyrone/badvpn/commit/3ce4233ca7d4feba803f2f3a2d288699e0ce9713

Other files are not modified, twip sources list can be obtained via newly added src/Filelists.mk

**Comment by wongsyrone** [comment]
There is a new opt called LWIP_SINGLE_NETIF, we can define this to reduce code footprint further.

tun2socks only use one netif named "ho0"; this option might be designed for tun2socks. :)

**Comment by ambrop72** [comment]
I tried to incorporate these changes but upon testing with Valgrind I'm seeing what might be memory leaks (TCP PCBs seems to be leaking, Valgrind claims "definitely lost"). I will investigate and push once that is resolved.

**Comment by wongsyrone** [comment]
> TCP PCBs seems to be leaking

might in tcp_in.c, but not sure

**Comment by ambrop72** [comment]
I analyzed this further and there is indeed a real leak. I filed a but report at lwIP: https://savannah.nongnu.org/bugs/index.php?52112

Technically it seems possible to work around it by avoiding calling tcp_close from lwIP callbacks but I hope it is fixed soon so I won't have to do that.

**Comment by ambrop72** [comment]
By the way, I am currently developing [my own TCP/IP stack](https://github.com/ambrop72/aipstack) and at some point I will just replace lwIP with that for tun2socks - hopefully that will be the end of having to deal with lwIP bugs and updates.

**Comment by wongsyrone** [comment]
it seems that leaking issue doesn't exist. Developing your own won't be a good idea, there is fewer people working on bugs and security flaws.

**Comment by ambrop72** [comment]
The leak definitely exists in the code you have, if you don't see it you have not tested enough. I found out it was caused by tun2socks code too often returning ERR_ABRT from callbacks. This was a workaround for an old lwIP bug which has since been fixed and the workaround was now causing the leak. I have fixed the issue and pushed the updated code to this repository. You probably want to sync at least the tun2socks.c changes.

> Developing your own won't be a good idea, there is fewer people working on bugs and security flaws.

My thing (which is already very functional) likely has orders of magnitude less bugs than lwIP, so I'll just keep working on it :) It doesn't yet have the "bind to all" function that is needed for tun2socks but that can be added easily.

**Comment by wongsyrone** [comment]
Well. I'm not able to write my own TCP/IP stack. As long as you keep maintaining this, there is no issue at all, but one day you stop supporting, only you can understand the whole thing.

**Comment by wongsyrone** [comment]
> This was a workaround for an old lwIP bug

I have little knowledge on tun2socks, I even don't know it was a workaround. My intention is just to make it work not bug-free since you said "Sorry I don't maintain this code regularly anymore."

I think it worth noting about the mechanism tun2socks uses, such as binding to all addresses and ports, etc. In this way, others can keep going if one day you decide to drop it. It is just a suggestion.
