### ISSUE TITLE
Mac OS X install BadVPN failed

### ISSUE THREAD

**Issue by LSsoftware** [ambrop72/badvpn#46]
Everything is running well before I enter the make command : make

```
[ 42%] Building C object system/CMakeFiles/system.dir/BSignal.c.o
In file included from /Users/Skinner/Documents/VPN/badvpn/system/BSignal.c:34:
/Users/Shoplex/Documents/VPN/badvpn/system/BUnixSignal.h:38:2: error: 
      Unknown signal backend or too many signal backends
#error Unknown signal backend or too many signal backends
 ^
In file included from /Users/Shoplex/Documents/VPN/badvpn/system/BSignal.c:34:
In file included from /Users/Shoplex/Documents/VPN/badvpn/system/BUnixSignal.h:45:
In file included from /Users/Shoplex/Documents/VPN/badvpn/system/BReactor.h:6:
/Users/Shoplex/Documents/VPN/badvpn/system/BReactor_badvpn.h:39:2: error: 
      Unknown event backend or too many event backends
#error Unknown event backend or too many event backends
 ^
2 errors generated.
make[2]: *** [system/CMakeFiles/system.dir/BSignal.c.o] Error 1
make[1]: *** [system/CMakeFiles/system.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ambrop72** [comment]
Mac OS X support is not supported. Which application do you need, tun2socks only? I remember someone getting tun2socks to work on OS X. But it needs some work. The errors here should not be hard to fix, you probably need to list modify the root CMakeLists.txt to define `-DBADVPN_USE_KEVENT` in case of compiling for OS X. The harder part is to get the TUN/TAP interface working.

It seems someone got something working on OS X some time ago (https://gitlab.com/linusyang/badvpn) but it was not contributed back. Seems like the TUNTAP part only supports TUN not TAP, so tun2socks would work but not badvpn-client.

**Comment by 0xv** [comment]
@ambrop72 how to compile tun2socks only in OS X?

**Comment by ambrop72** [comment]
closing, unless someone contributes code there is no OSX support
