### ISSUE TITLE
Cannot compile on Linux

### ISSUE THREAD

**Issue by M0xkLurk3r** [ambrop72/badvpn#47]
I'd download the latest source and tried to compile tun2socks, but finally it throws me a error:

|-------------- Terminal output ------------------|
<0> [anthony@ZONGYI-NOTEBOOK /home/blocker/workingdir/download_source] $ git clone https://github.com/ambrop72/badvpn
Cloning into 'badvpn'...
remote: Counting objects: 14479, done.
remote: Total 14479 (delta 0), reused 0 (delta 0), pack-reused 14479
Receiving objects: 100% (14479/14479), 4.74 MiB | 674.00 KiB/s, done.
Resolving deltas: 100% (11113/11113), done.
<0> [anthony@ZONGYI-NOTEBOOK /home/blocker/workingdir/download_source] $ cd badvpn/
<0> [anthony@ZONGYI-NOTEBOOK /home/blocker/workingdir/download_source/badvpn] $ mkdir build
<0> [anthony@ZONGYI-NOTEBOOK /home/blocker/workingdir/download_source/badvpn] $ cd build
<0> [anthony@ZONGYI-NOTEBOOK /home/blocker/workingdir/download_source/badvpn/build] $ ENDIAN=little CC=gcc SRCDIR=../ ../compile-tun2sock.sh

/* Omitting compile output */

+ OBJS=("${OBJS[@]}" "${obj}")
+ gcc BLog_syslog.c.o BReactor_badvpn.c.o BSignal.c.o BConnection_unix.c.o BConnection_common.c.o BTime.c.o BUnixSignal.c.o BNetwork.c.o BDatagram_unix.c.o StreamRecvInterface.c.o PacketRecvInterface.c.o PacketPassInterface.c.o StreamPassInterface.c.o SinglePacketBuffer.c.o BufferWriter.c.o PacketBuffer.c.o PacketStreamSender.c.o PacketPassConnector.c.o PacketProtoFlow.c.o PacketPassFairQueue.c.o PacketProtoEncoder.c.o PacketProtoDecoder.c.o BSocksClient.c.o BTap.c.o timers.c.o udp.c.o memp.c.o init.c.o pbuf.c.o tcp.c.o tcp_out.c.o netif.c.o def.c.o mem.c.o tcp_in.c.o stats.c.o inet_chksum.c.o icmp.c.o ip4.c.o ip4_addr.c.o ip_frag.c.o ip6.c.o nd6.c.o icmp6.c.o ip6_addr.c.o ip6_frag.c.o sys.c.o tun2socks.c.o DebugObject.c.o BLog.c.o BPending.c.o PacketPassInactivityMonitor.c.o SocksUdpGwClient.c.o UdpGwClient.c.o -o ./tun2socks -lrt
/usr/bin/ld: BUnixSignal.c.o: undefined reference to symbol 'pthread_sigmask@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
<1> [anthony@ZONGYI-NOTEBOOK /home/blocker/workingdir/download_source/badvpn/build] $ 
|------------- Cut here ----------------------|

Maybe something troubled with my ld. here is my system information:

|-------------- Terminal output ---------------|
<0> [anthony@ZONGYI-NOTEBOOK /home/blocker/workingdir/download_source/badvpn/build] $ gcc --version
gcc (Debian 6.3.0-18) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

<0> [anthony@ZONGYI-NOTEBOOK /home/blocker/workingdir/download_source/badvpn/build] $ ld -V
GNU ld (GNU Binutils for Debian) 2.28
  Supported emulations:
   elf_x86_64
   elf32_x86_64
   elf_i386
   elf_iamcu
   i386linux
   elf_l1om
   elf_k1om
   i386pep
   i386pe
<0> [anthony@ZONGYI-NOTEBOOK /home/blocker/workingdir/download_source/badvpn/build] $ uname -a
Linux ZONGYI-NOTEBOOK 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
<0> [anthony@ZONGYI-NOTEBOOK /home/blocker/workingdir/download_source/badvpn/build] $ 
|------------ Cut here ---------------|

Hope for fix.

**Comment by ambrop72** [comment]
Fixed by 7300026cd8e395e3a98424fdb8b97ad2095b3ebe
