### ISSUE TITLE
Under Visual Studio 2017(cl.exe) building Release version cause error C2016

### ISSUE THREAD

**Issue by GreatFireWall** [ambrop72/badvpn#55]
a lot of "error c2016 c requires that a struct or union has at least one member" debugxxx.h files.

```
/**
 * Object used for detecting leaks.
 */
typedef struct {
    #ifndef NDEBUG
    uint32_t c;
    #endif
} DebugObject;
```

maybe cl.exe not allow empty struct ?

**Comment by ambrop72** [comment]
Indeed, thanks for reporting, I will fix it shortly. In the mean time you can simply remove the `#ifndef` and `#endif` around the variable.

**Comment by GreatFireWall** [comment]
BTW, the other statement not allow too 😢  :
```
struct _BLog_channel blog_channel_list[] = {
#include <generated/blog_channels_list.h>
};
```

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
if i comment out every `#ifndef NDEBUG` it compiles. Still looking forward for the told fix.

**Comment by ambrop72** [comment]
I've fixed the build problem and wrote new build instructions for Visual Studio (BUILD-WINDOWS-VisualStudio.md).
