### ISSUE TITLE
tun2socks to forward udp

### ISSUE THREAD

**Issue by dragonzhi** [ambrop72/badvpn#57]
hi

I want to use tun2socks to forward tcp and udp.
With test, I found tcp forward success.
for udp,I run badvpn-tun2socks.exe with --udpgw-remote-server-addr and run badvpn-udpgw.exe on the same socks client,but udp can't forward.

could you pls help me with it?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
badvpn-udpgw.exe needs to be reachable from the same socks server, the client is connected too as far i know

**Comment by ambrop72** [comment]
There is far too little info here to say anything, I'm closing this.
