### ISSUE TITLE
Release build of tun2socks request

### ISSUE THREAD

**Issue by bitching** [ambrop72/badvpn#58]
have built windows version tun2socks by following the guide, but it's a debug build and it requires VCRUNTIME140D.dll
this dll is not included in Visual C++ Redistributable 2017.
please provide us a release build.
Thanks in advance.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
just build the release version the same way, what's wrong?

**Comment by ambrop72** [comment]
You can build it yourself by following the new build instructions in `BUILD-WINDOWS-VisualStudio.md`. I will not be providing builds.
