### ISSUE TITLE
Is Possible to lockdown the virtual tun2socks router, to accept only local host connections?

### ISSUE THREAD

**Issue by neimanpinchas** [ambrop72/badvpn#59]
I am running tun2socks on a windows 7 machine, which is a plugged into my public ip address

The machine also runs nat32 which does the nat and routing to all my home computers.

Suddenly i found in nat32 a big list of unknown devices (ipads, iphones....) connected to the 10.0.0 subnet (the tun2socks router).

Question #1 is, is even there a possibility to connect to that router from an outside device?

Question #2 Is there a way to lock down the virtual router?

**Comment by ambrop72** [comment]
In the current tun2socks implementation, there is no feature for access control. You may find one in your operating system. Maybe look into the Windows Firewall advanced configuration. I couldn't help further.
