### ISSUE TITLE
Is Possible to forward HTTP with tun2socks?

### ISSUE THREAD

**Issue by askdaddy** [ambrop72/badvpn#60]
Now I use tun2socks forward tcp in Android.
Is there any better way to forward http traffic to a proxy server?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
why? tun2socks is the best way  in my honest opinion already

**Comment by ambrop72** [comment]
Tun2socks uses an embedded lwIP network stack to translate between packets and the SOCKS server. It is a "hacky" solution and not ideal, including from a performance perspective. I do not know of other solutions that would work on Android.
