### ISSUE TITLE
INFO(SocksUdpGwClient): SOCKS error

### ISSUE THREAD

**Issue by faqin** [ambrop72/badvpn#63]
Hi
badvpn_udpgw run on romate server(Cenos 7 ,ip:45.63.xxx.xxx):
`./badvpn-udpgw --listen-addr 127.0.0.1:7300 `

tun2socks run on windows
`tun2socks.exe --tundev tap0901:"adapter 2":10.0.0.1:10.0.0.0:255.255.255.0 --netif-ipaddr 10.0.0.2  --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:1080   --udpgw-remote-server-addr 45.63.xxx.xxx:7300 `

socks server is 45.63.xxx.xxx,too. use shadowsocksr : https://github.com/shadowsocksrr
router table cmd:
`
netsh interface ip set interface "Ethernet0" ignoredefaultroutes=enabled
`
`
route add 45.63.xxx.xxx 172.16.213.2 metric 5
`

I get this error:

NOTICE(tun2socks): entering event loop
INFO(SocksUdpGwClient): SOCKS up
INFO(SocksUdpGwClient): SOCKS error
INFO(SocksUdpGwClient): SOCKS up
INFO(SocksUdpGwClient): SOCKS error

what's meaning of this error and how do I resolve it?
Thank you!

**Comment by ambrop72** [comment]
Looks like a problem with the SOCKS server. Best to check the traffic with wireshark or similar. I cannot help further since it is such a generic error.

**Comment by zhaoguomanong** [comment]
I got the same error when forwarding UDP. socks client and server use v2ray.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
RTFM not support shadowsocks or v2ray!

**Comment by zhaoguomanong** [comment]
@4-FLOSS-Free-Libre-Open-Source-Software 

https://github.com/eycorsican/go-tun2socks  support all sock5 proxy, both tcp and udp and icmp
