### ISSUE TITLE
Cannot stop tun2socks by CTRL-C on MacOS.

### ISSUE THREAD

**Issue by david9991** [ambrop72/badvpn#65]
Cannot stop tun2socks by CTRL-C on MacOS.
it stuck at
```
2018/05/23 08:26:30 quit tun2socks writer
```

**Comment by david9991** [comment]
And I tried to execute: `ping 10.0.0.1`
it stopped with error message
```
2018/05/23 08:29:49 Unsupported packet: protocol 1
2018/05/23 08:29:49 read packet error: read utun3: file already closed
```

**Comment by ambrop72** [comment]
Hey
Tun2socks in this repository does not support MacOS. I don't know what you are using, I cannot help with third-party modifications.

**Comment by david9991** [comment]
Oh sorry, I'm using gotun2socks, wrong repository I went. XD
