### ISSUE TITLE
building error on windows

### ISSUE THREAD

**Issue by malikshi** [ambrop72/badvpn#67]
**i am using VS 2017 and cmake to build but error while built to target there the lod **
E:\badvpn-build>cmake --build . --target install
Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 8/29/2018 5:16:38 PM.
Project "E:\badvpn-build\install.vcxproj" on node 1 (default targets).
Project "E:\badvpn-build\install.vcxproj" (1) is building "E:\badvpn-build\ZERO_CHECK.vcxproj" (2) on node 1 (default t
argets).
InitializeBuildStatus:
  Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "E:\badvpn-build\ZERO_CHECK.vcxproj" (default targets).

Project "E:\badvpn-build\install.vcxproj" (1) is building "E:\badvpn-build\ALL_BUILD.vcxproj" (3) on node 1 (default ta
rgets).
Project "E:\badvpn-build\ALL_BUILD.vcxproj" (3) is building "E:\badvpn-build\tun2socks\badvpn-tun2socks.vcxproj" (4) on
 node 1 (default targets).
Project "E:\badvpn-build\tun2socks\badvpn-tun2socks.vcxproj" (4) is building "E:\badvpn-build\base\base.vcxproj" (5) on
 node 1 (default targets).
InitializeBuildStatus:
  Creating "base.dir\Debug\base.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  All outputs are up-to-date.
Lib:
  All outputs are up-to-date.
  base.vcxproj -> E:\badvpn-build\base\Debug\badvpn-base.lib
FinalizeBuildStatus:
  Deleting file "base.dir\Debug\base.tlog\unsuccessfulbuild".
  Touching "base.dir\Debug\base.tlog\base.lastbuildstate".
Done Building Project "E:\badvpn-build\base\base.vcxproj" (default targets).

Project "E:\badvpn-build\tun2socks\badvpn-tun2socks.vcxproj" (4) is building "E:\badvpn-build\flow\flow.vcxproj" (6) on
 node 1 (default targets).
InitializeBuildStatus:
  Creating "flow.dir\Debug\flow.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  All outputs are up-to-date.
Lib:
  All outputs are up-to-date.
  flow.vcxproj -> E:\badvpn-build\flow\Debug\badvpn-flow.lib
FinalizeBuildStatus:
  Deleting file "flow.dir\Debug\flow.tlog\unsuccessfulbuild".
  Touching "flow.dir\Debug\flow.tlog\flow.lastbuildstate".
Done Building Project "E:\badvpn-build\flow\flow.vcxproj" (default targets).

Project "E:\badvpn-build\tun2socks\badvpn-tun2socks.vcxproj" (4) is building "E:\badvpn-build\flowextra\flowextra.vcxpr
oj" (7) on node 1 (default targets).
Project "E:\badvpn-build\flowextra\flowextra.vcxproj" (7) is building "E:\badvpn-build\system\system.vcxproj" (8) on no
de 1 (default targets).
InitializeBuildStatus:
  Touching "system.dir\Debug\system.tlog\unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\CL.exe /c /I
  "E:\badvpn-1.999.130" /I"E:\badvpn-1.999.130\lwip\custom" /I"E:\badvpn-1.999.130\lwip\src\include" /I"E:\badvpn-1.999
  .130\lwip\src\include\ipv4" /I"E:\badvpn-1.999.130\lwip\src\include\ipv6" /Zi /nologo /W3 /WX- /diagnostics:classic /
  Od /Ob0 /D WIN32 /D _WINDOWS /D BADVPN_BREACTOR_BADVPN /D _CRT_SECURE_NO_WARNINGS /D BADVPN_USE_WINAPI /D _WIN32_WINN
  T=0x600 /D WIN32_LEAN_AND_MEAN /D BADVPN_THREAD_SAFE=0 /D BADVPN_LITTLE_ENDIAN /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /
  Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"system.dir\Debug\\" /Fd"system.dir\Debug\syste
  m.pdb" /Gd /TP /wd4065 /wd4018 /wd4533 /wd4244 /wd4102 /FC /errorReport:queue "E:\badvpn-1.999.130\system\BConnection
  _common.c" "E:\badvpn-1.999.130\system\BConnection_win.c" "E:\badvpn-1.999.130\system\BDatagram_win.c"
  BConnection_common.c
e:\badvpn-1.999.130\system\baddr.h(320): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible los
s of data [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(459): error C3688: invalid literal suffix 'PRIu8'; literal operator or literal opera
tor template 'operator ""PRIu8' not found [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(459): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conver
t argument 2 from 'uint8_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(464): note: Conversion from integral type to pointer type requires reinterpret_cas
  t, C-style cast or function-style cast
e:\badvpn-1.999.130\system\baddr.h(470): error C3688: invalid literal suffix 'PRIx16'; literal operator or literal oper
ator template 'operator ""PRIx16' not found [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(468): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conver
t argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(479): note: Conversion from integral type to pointer type requires reinterpret_cas
  t, C-style cast or function-style cast
e:\badvpn-1.999.130\system\baddr.h(604): error C3688: invalid literal suffix 'PRIu16'; literal operator or literal oper
ator template 'operator ""PRIu16' not found [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(604): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conver
t argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(604): note: Conversion from integral type to pointer type requires reinterpret_cas
  t, C-style cast or function-style cast
e:\badvpn-1.999.130\system\baddr.h(609): error C3688: invalid literal suffix 'PRIu16'; literal operator or literal oper
ator template 'operator ""PRIu16' not found [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(609): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conver
t argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(609): note: Conversion from integral type to pointer type requires reinterpret_cas
  t, C-style cast or function-style cast
e:\badvpn-1.999.130\system\baddr.h(627): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible los
s of data [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\misc\bsize.h(63): warning C4838: conversion from 'int' to 'size_t' requires a narrowing conversion
[E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\misc\bsize.h(93): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [E:\
badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\base\blog.h(246): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data [E:
\badvpn-build\system\system.vcxproj]
  BConnection_win.c
e:\badvpn-1.999.130\misc\bsize.h(63): warning C4838: conversion from 'int' to 'size_t' requires a narrowing conversion
[E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\misc\bsize.h(93): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [E:\
badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\base\blog.h(246): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data [E:
\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(320): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible los
s of data [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(459): error C3688: invalid literal suffix 'PRIu8'; literal operator or literal opera
tor template 'operator ""PRIu8' not found [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(459): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conver
t argument 2 from 'uint8_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(464): note: Conversion from integral type to pointer type requires reinterpret_cas
  t, C-style cast or function-style cast
e:\badvpn-1.999.130\system\baddr.h(470): error C3688: invalid literal suffix 'PRIx16'; literal operator or literal oper
ator template 'operator ""PRIx16' not found [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(468): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conver
t argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(479): note: Conversion from integral type to pointer type requires reinterpret_cas
  t, C-style cast or function-style cast
e:\badvpn-1.999.130\system\baddr.h(604): error C3688: invalid literal suffix 'PRIu16'; literal operator or literal oper
ator template 'operator ""PRIu16' not found [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(604): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conver
t argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(604): note: Conversion from integral type to pointer type requires reinterpret_cas
  t, C-style cast or function-style cast
e:\badvpn-1.999.130\system\baddr.h(609): error C3688: invalid literal suffix 'PRIu16'; literal operator or literal oper
ator template 'operator ""PRIu16' not found [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(609): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conver
t argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(609): note: Conversion from integral type to pointer type requires reinterpret_cas
  t, C-style cast or function-style cast
e:\badvpn-1.999.130\system\baddr.h(627): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible los
s of data [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\bconnection_win.c(153): warning C4996: 'WSASocketA': Use WSASocketW() instead or define _WIN
SOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [E:\badvpn-build\system\system.vcxproj]
  e:\windows kits\10\include\10.0.17134.0\um\winsock2.h(3415): note: see declaration of 'WSASocketA'
e:\badvpn-1.999.130\system\bconnection_win.c(467): warning C4996: 'WSASocketA': Use WSASocketW() instead or define _WIN
SOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [E:\badvpn-build\system\system.vcxproj]
  e:\windows kits\10\include\10.0.17134.0\um\winsock2.h(3415): note: see declaration of 'WSASocketA'
e:\badvpn-1.999.130\system\bconnection_win.c(594): warning C4996: 'WSASocketA': Use WSASocketW() instead or define _WIN
SOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [E:\badvpn-build\system\system.vcxproj]
  e:\windows kits\10\include\10.0.17134.0\um\winsock2.h(3415): note: see declaration of 'WSASocketA'
  BDatagram_win.c
e:\badvpn-1.999.130\misc\bsize.h(63): warning C4838: conversion from 'int' to 'size_t' requires a narrowing conversion
[E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\misc\bsize.h(93): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [E:\
badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\base\blog.h(246): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data [E:
\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(320): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible los
s of data [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(459): error C3688: invalid literal suffix 'PRIu8'; literal operator or literal opera
tor template 'operator ""PRIu8' not found [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(459): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conver
t argument 2 from 'uint8_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(464): note: Conversion from integral type to pointer type requires reinterpret_cas
  t, C-style cast or function-style cast
e:\badvpn-1.999.130\system\baddr.h(470): error C3688: invalid literal suffix 'PRIx16'; literal operator or literal oper
ator template 'operator ""PRIx16' not found [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(468): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conver
t argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(479): note: Conversion from integral type to pointer type requires reinterpret_cas
  t, C-style cast or function-style cast
e:\badvpn-1.999.130\system\baddr.h(604): error C3688: invalid literal suffix 'PRIu16'; literal operator or literal oper
ator template 'operator ""PRIu16' not found [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(604): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conver
t argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(604): note: Conversion from integral type to pointer type requires reinterpret_cas
  t, C-style cast or function-style cast
e:\badvpn-1.999.130\system\baddr.h(609): error C3688: invalid literal suffix 'PRIu16'; literal operator or literal oper
ator template 'operator ""PRIu16' not found [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\baddr.h(609): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conver
t argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(609): note: Conversion from integral type to pointer type requires reinterpret_cas
  t, C-style cast or function-style cast
e:\badvpn-1.999.130\system\baddr.h(627): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible los
s of data [E:\badvpn-build\system\system.vcxproj]
e:\badvpn-1.999.130\system\bdatagram_win.c(497): warning C4996: 'WSASocketA': Use WSASocketW() instead or define _WINSO
CK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [E:\badvpn-build\system\system.vcxproj]
  e:\windows kits\10\include\10.0.17134.0\um\winsock2.h(3415): note: see declaration of 'WSASocketA'
  Generating Code...
Done Building Project "E:\badvpn-build\system\system.vcxproj" (default targets) -- FAILED.

Done Building Project "E:\badvpn-build\flowextra\flowextra.vcxproj" (default targets) -- FAILED.

Done Building Project "E:\badvpn-build\tun2socks\badvpn-tun2socks.vcxproj" (default targets) -- FAILED.

Done Building Project "E:\badvpn-build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Done Building Project "E:\badvpn-build\install.vcxproj" (default targets) -- FAILED.

Build FAILED.

"E:\badvpn-build\install.vcxproj" (default target) (1) ->
"E:\badvpn-build\ALL_BUILD.vcxproj" (default target) (3) ->
"E:\badvpn-build\tun2socks\badvpn-tun2socks.vcxproj" (default target) (4) ->
"E:\badvpn-build\flowextra\flowextra.vcxproj" (default target) (7) ->
"E:\badvpn-build\system\system.vcxproj" (default target) (8) ->
(ClCompile target) ->
  e:\badvpn-1.999.130\system\baddr.h(320): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible l
oss of data [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(627): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible l
oss of data [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\misc\bsize.h(63): warning C4838: conversion from 'int' to 'size_t' requires a narrowing conversio
n [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\misc\bsize.h(93): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [E
:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\base\blog.h(246): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data [
E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\misc\bsize.h(63): warning C4838: conversion from 'int' to 'size_t' requires a narrowing conversio
n [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\misc\bsize.h(93): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [E
:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\base\blog.h(246): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data [
E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(320): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible l
oss of data [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(627): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible l
oss of data [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\bconnection_win.c(153): warning C4996: 'WSASocketA': Use WSASocketW() instead or define _W
INSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\bconnection_win.c(467): warning C4996: 'WSASocketA': Use WSASocketW() instead or define _W
INSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\bconnection_win.c(594): warning C4996: 'WSASocketA': Use WSASocketW() instead or define _W
INSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\misc\bsize.h(63): warning C4838: conversion from 'int' to 'size_t' requires a narrowing conversio
n [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\misc\bsize.h(93): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [E
:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\base\blog.h(246): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data [
E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(320): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible l
oss of data [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(627): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible l
oss of data [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\bdatagram_win.c(497): warning C4996: 'WSASocketA': Use WSASocketW() instead or define _WIN
SOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [E:\badvpn-build\system\system.vcxproj]

"E:\badvpn-build\install.vcxproj" (default target) (1) ->
"E:\badvpn-build\ALL_BUILD.vcxproj" (default target) (3) ->
"E:\badvpn-build\tun2socks\badvpn-tun2socks.vcxproj" (default target) (4) ->
"E:\badvpn-build\flowextra\flowextra.vcxproj" (default target) (7) ->
"E:\badvpn-build\system\system.vcxproj" (default target) (8) ->
(ClCompile target) ->
  e:\badvpn-1.999.130\system\baddr.h(459): error C3688: invalid literal suffix 'PRIu8'; literal operator or literal ope
rator template 'operator ""PRIu8' not found [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(459): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conv
ert argument 2 from 'uint8_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(470): error C3688: invalid literal suffix 'PRIx16'; literal operator or literal op
erator template 'operator ""PRIx16' not found [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(468): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conv
ert argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(604): error C3688: invalid literal suffix 'PRIu16'; literal operator or literal op
erator template 'operator ""PRIu16' not found [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(604): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conv
ert argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(609): error C3688: invalid literal suffix 'PRIu16'; literal operator or literal op
erator template 'operator ""PRIu16' not found [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(609): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conv
ert argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(459): error C3688: invalid literal suffix 'PRIu8'; literal operator or literal ope
rator template 'operator ""PRIu8' not found [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(459): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conv
ert argument 2 from 'uint8_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(470): error C3688: invalid literal suffix 'PRIx16'; literal operator or literal op
erator template 'operator ""PRIx16' not found [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(468): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conv
ert argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(604): error C3688: invalid literal suffix 'PRIu16'; literal operator or literal op
erator template 'operator ""PRIu16' not found [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(604): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conv
ert argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(609): error C3688: invalid literal suffix 'PRIu16'; literal operator or literal op
erator template 'operator ""PRIu16' not found [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(609): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conv
ert argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(459): error C3688: invalid literal suffix 'PRIu8'; literal operator or literal ope
rator template 'operator ""PRIu8' not found [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(459): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conv
ert argument 2 from 'uint8_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(470): error C3688: invalid literal suffix 'PRIx16'; literal operator or literal op
erator template 'operator ""PRIx16' not found [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(468): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conv
ert argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(604): error C3688: invalid literal suffix 'PRIu16'; literal operator or literal op
erator template 'operator ""PRIu16' not found [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(604): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conv
ert argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(609): error C3688: invalid literal suffix 'PRIu16'; literal operator or literal op
erator template 'operator ""PRIu16' not found [E:\badvpn-build\system\system.vcxproj]
  e:\badvpn-1.999.130\system\baddr.h(609): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot conv
ert argument 2 from 'uint16_t' to 'const char *const ' [E:\badvpn-build\system\system.vcxproj]

    19 Warning(s)
    24 Error(s)

Time Elapsed 00:00:02.49

E:\badvpn-build>

**Comment by ambrop72** [comment]
It now builds in VS2017, please see the new build instructions in `BUILD-WINDOWS-VisualStudio.md`.
