### ISSUE TITLE
udp forward by stun client will not be open

### ISSUE THREAD

**Issue by ZhYuLn** [ambrop72/badvpn#69]
hello, I forward udp by udpgw and --udpgw-remote-server-addr. when the connect finish, the udpgw will build a port for this connection, when I use nc to test this port, the udpgw client will not get the right source. Just like this:

udpclient(10.0.0.2) :10000 >>>>8.8.4.4:53----->udpgw(1.1.1.1:7300):20000------> 8.8.4.4:53
nc test(2.2.2.2):10001 >>>> udpgw(1.1.1.1):20000 --------> udpclient:10000 -->source by 8.8.4.4:53

the udpclient can't known that the source is 2.2.2.2 , it think the source is 8.8.4.4

**Comment by ambrop72** [comment]
By design, udpgw does not preserve the source address. It is not possible to solve, by the nature of what tun2socks/udpgw is doing.
