### ISSUE TITLE
Is this possible: tun2socks with netns for torrent client?

### ISSUE THREAD

**Issue by mgaulton** [ambrop72/badvpn#70]
Hey there, 
I'm trying to verify if my thinking is right and see if you can give some guidance here.
I want to isolate a torrent client so that they can only talk to a tun0 interface linked to my socks proxy by tun2socks in its own network namespace, rather than relying on user iptables rules.

I'm wondering a couple of things:
1. does tun2socks support all torrenting traffic as is?
2. from the network namespace, I believe I need to build a bridge adapter, to link the inside interface to the outside tun0. I have created the tun0 and migrated it into the namespace but get no route to host. 
3. Any suggestions or things I missed?

**Comment by mgaulton** [comment]
The reference I'm trying to follow btw 
https://unix.stackexchange.com/questions/266114/how-can-i-constrain-a-user-application-to-always-run-in-a-particular-network-nam

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
1. Yes

**Comment by ambrop72** [comment]
Yes, the whole point of tun2socks is that it deals with all traffic. Sorry that I cannot help you with network namespaces. If you get no route to host, best to check your routing tables.
