### ISSUE TITLE
[Copyright issues] I find that commercial companies seem to be using tun2socket

### ISSUE THREAD

**Issue by jhoneybee** [ambrop72/badvpn#80]
+ https://uu.163.com/  Corporate name

There is a tun2proxy.dll in the directory

![image](https://user-images.githubusercontent.com/24241052/60693702-e3fe5d00-9f0d-11e9-8767-af8bd70f9e32.png)

> The way his program works seems to be tun/tap ->socket5  conversion. I suspect that it uses open source tun2socket code and does not follow the corresponding open source protocol.

**Comment by jhoneybee** [comment]
@ambrop72

**Comment by duncanokeyo** [comment]
badvpn uses BSD licence which according to my own understanding is okay to use in commercial products as long as attribution is given

**Comment by jhoneybee** [comment]
It's not clear whether the'tun2soket'code is used, but I think the author's signature should be retained, apparently not in the document.
