### ISSUE TITLE
UDP redirection with iptables ?

### ISSUE THREAD

**Issue by lepasserby** [ambrop72/badvpn#9]
Hi!
Coming here from Shadowsocks (who use the tun2socks, among other things, under the hood)

I'm trying to achieve the following:

1) Force UDP AND TCP traffic that is going to a specific remote port to go through the shadowsocks proxy
2) Force UDP AND TCP traffic originating from a specific port range to go through the shadowsocks  proxy

I suspect I could achieve that with tun2socks (which is included with Shadowsocks) but damn me if I knew how. Iptables be killin me

**Comment by ambrop72** [comment]
Hey,

This gets asked a lot... Tun2socks cannot control what comes into the TAP interface, this is up to the OS. On Linux technically you can control this with some advanced mechanisms. "ip rule" allows you to use a different routing table based on various parameters including iptables marks. Generally the feature is called "policy based routing" and I'm sure you can find information about it around the net.

**Comment by lepasserby** [comment]
Thanks! 
Though in the interest of fairness I've gotta say that policy based routing is a world of pain :(

**Comment by ambrop72** [comment]
Closing, not an issue with tun2socks.
