### ISSUE TITLE
reconnection result netif not found

### ISSUE THREAD

**Issue by xDragonZ** [ambrop72/badvpn#92]
Building tun2socks for android with `BUILD_SHARED_LIBRARY` (.so) will result in no network connection after 2nd reconnection attempt unless we quit/kill the app.

Added this code in `tun2socks.c` (lwip_init_job_handler)
```
    struct netif *netif = netif_find("ho0");
    if (netif == NULL) {
        BLog(BLOG_ERROR, "netif_find failed");
        goto fail;
    }
```
it will show "netif_find failed" 

--------------

Manage to get it resolved by using `define LWIP_SINGLE_NETIF 1` 

Tried porting badvpn `netif_set_pretend_tcp` related changes with latest lwip commit from https://github.com/lwip-tcpip/lwip still result the same error.

**Comment by xDragonZ** [comment]
After collecting some crash log from play store.

found it is randomly throwing, if we define LWIP_SINGLE_NETIF

> LWIP_ASSERT("single netif already set", 0);

in netif.c file

**Comment by xDragonZ** [comment]
bump

**Comment by ambrop72** [comment]
I think that lwIP is not designed to be reinitialized. You would need to find all lwIP global variables and set them to their default state if lwIP code relies on them being initialized.

**Comment by xDragonZ** [comment]
Thanks, by the way how's the progress for custom lwip that you are working on?
